apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cdutten/argo-deployments.git
    targetRevision: HEAD
    path: apps/nginx-test
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test