apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cdutten/argodeployments.git
    targetRevision: HEAD
    path: apps/argo-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd